version: 2
jobs:
  build:
    working_directory: ~/AndroidDemo/app
    docker:
          
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout  
      - restore_cache:
          key: jars-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./AndroidDemo/gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
      - run:
          name: Run EspressoTests
          command: ./AndroidDemo/gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
